In [1]:
import numpy as np

from my_functions import *
import pandas as pd

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

import os
from dotenv import load_dotenv

load_dotenv("parameters.env")
username = os.getenv("USERTAG")
username

'rajakel'

In [2]:
#username = "rajakel"
my_games = import_games(f"{username}_all_games.pgn")

In [3]:
my_openings = {}

for id, game in my_games.items():
    temp_opening = game["ECO"]
    if temp_opening in my_openings:
        my_openings[temp_opening]["count"] += 1
    else:
        my_openings[temp_opening]  = {"name": game["ECOUrl"].split(r"/")[-1].replace("-", " ") , "count" : 0, "link" : game["ECOUrl"]}
    my_games[id]["Opening"] = my_openings[temp_opening]["name"]
my_openings = dict(sorted(my_openings.items(), key = lambda x : x[1]["count"], reverse = True))
my_openings

{'B01': {'name': 'Scandinavian Defense Mieses Kotrc Main Line 4.d4 c6 5.Nf3 Bf5',
  'count': 2211,
  'link': 'https://www.chess.com/openings/Scandinavian-Defense-Mieses-Kotrc-Main-Line-4.d4-c6-5.Nf3-Bf5'},
 'B07': {'name': 'Pirc Defense 2.Nc3 Nf6',
  'count': 839,
  'link': 'https://www.chess.com/openings/Pirc-Defense-2.Nc3-Nf6'},
 'C20': {'name': 'Kings Pawn Opening 1...e5',
  'count': 743,
  'link': 'https://www.chess.com/openings/Kings-Pawn-Opening-1...e5'},
 'C00': {'name': 'French Defense Queens Knight Variation',
  'count': 701,
  'link': 'https://www.chess.com/openings/French-Defense-Queens-Knight-Variation'},
 'B00': {'name': 'Owens Defense 2.Nc3 Bb7',
  'count': 603,
  'link': 'https://www.chess.com/openings/Owens-Defense-2.Nc3-Bb7'},
 'A00': {'name': 'Van t Kruijs Opening 1...e5',
  'count': 505,
  'link': 'https://www.chess.com/openings/Van-t-Kruijs-Opening-1...e5'},
 'C34': {'name': 'Kings Gambit Accepted Schallopp Defense 4.Nc3',
  'count': 379,
  'link': 'https://www.chess.com/openings/Kings-Gambit-Accepted-Schallopp-Defense-4.Nc3'},
 'C25': {'name': 'Vienna Game Max Lange Vienna Gambit',
  'count': 371,
  'link': 'https://www.chess.com/openings/Vienna-Game-Max-Lange-Vienna-Gambit'},
 'D00': {'name': 'Queens Pawn Opening 1...d5 2.e3',
  'count': 361,
  'link': 'https://www.chess.com/openings/Queens-Pawn-Opening-1...d5-2.e3'},
 'C30': {'name': 'Kings Gambit',
  'count': 307,
  'link': 'https://www.chess.com/openings/Kings-Gambit'},
 'A40': {'name': 'Modern Defense with 1 d4...3.Bf4 d6 4.e3 Nf6',
  'count': 267,
  'link': 'https://www.chess.com/openings/Modern-Defense-with-1-d4...3.Bf4-d6-4.e3-Nf6'},
 'C23': {'name': 'Bishops Opening',
  'count': 205,
  'link': 'https://www.chess.com/openings/Bishops-Opening'},
 'B06': {'name': 'Modern Defense with 1 e4...3.Nf3 d6 4.Bc4 Nf6 5.Nc3',
  'count': 199,
  'link': 'https://www.chess.com/openings/Modern-Defense-with-1-e4...3.Nf3-d6-4.Bc4-Nf6-5.Nc3'},
 'B10': {'name': 'Caro Kann Defense 2.Nc3 d5',
  'count': 169,
  'link': 'https://www.chess.com/openings/Caro-Kann-Defense-2.Nc3-d5'},
 'D02': {'name': 'Queens Pawn Opening Zukertort Variation 2...e6 3.Bf4 c5 4.e3',
  'count': 161,
  'link': 'https://www.chess.com/openings/Queens-Pawn-Opening-Zukertort-Variation-2...e6-3.Bf4-c5-4.e3'},
 'B08': {'name': 'Pirc Defense Classical Variation 4...Bg7',
  'count': 157,
  'link': 'https://www.chess.com/openings/Pirc-Defense-Classical-Variation-4...Bg7'},
 'C50': {'name': 'Italian Game 3...d6',
  'count': 133,
  'link': 'https://www.chess.com/openings/Italian-Game-3...d6'},
 'B02': {'name': 'Alekhines Defense 2.Nc3',
  'count': 119,
  'link': 'https://www.chess.com/openings/Alekhines-Defense-2.Nc3'},
 'A45': {'name': 'Trompowsky Attack 2...d6',
  'count': 117,
  'link': 'https://www.chess.com/openings/Trompowsky-Attack-2...d6'},
 'C28': {'name': 'Bishops Opening Berlin Vienna Hybrid Variation 4...Bc5 5.f4',
  'count': 111,
  'link': 'https://www.chess.com/openings/Bishops-Opening-Berlin-Vienna-Hybrid-Variation-4...Bc5-5.f4'},
 'A48': {'name': 'Indian Game East Indian London System 3...Bg7 4.e3',
  'count': 95,
  'link': 'https://www.chess.com/openings/Indian-Game-East-Indian-London-System-3...Bg7-4.e3'},
 'B22': {'name': 'Alapin Sicilian Defense 2...e6 3.d4',
  'count': 85,
  'link': 'https://www.chess.com/openings/Alapin-Sicilian-Defense-2...e6-3.d4'},
 'A41': {'name': 'Queens Pawn Opening 1...d6',
  'count': 85,
  'link': 'https://www.chess.com/openings/Queens-Pawn-Opening-1...d6'},
 'C26': {'name': 'Vienna Game Falkbeer Variation',
  'count': 75,
  'link': 'https://www.chess.com/openings/Vienna-Game-Falkbeer-Variation'},
 'B20': {'name': 'Sicilian Defense Bowdler Attack 2...e6',
  'count': 71,
  'link': 'https://www.chess.com/openings/Sicilian-Defense-Bowdler-Attack-2...e6'},
 'C47': {'name': 'Four Knights Game',
  'count': 71,
  'link': 'https://www.chess.com/openings/Four-Knights-Game'},
 'A04': {'name': 'Reti Opening',
  'count': 69,
  'link': 'https://www.chess.com/openings/Reti-Opening'},
 'C44': {'name': 'Ponziani Opening 3...d6 4.d4',
  'count': 69,
  'link': 'https://www.chess.com/openings/Ponziani-Opening-3...d6-4.d4'},
 'A01': {'name': 'Nimzowitsch Larsen Attack Indian Variation 2.Bb2 d6',
  'count': 51,
  'link': 'https://www.chess.com/openings/Nimzowitsch-Larsen-Attack-Indian-Variation-2.Bb2-d6'},
 'C01': {'name': 'French Defense Exchange Variation 3...exd5 4.Nc3',
  'count': 43,
  'link': 'https://www.chess.com/openings/French-Defense-Exchange-Variation-3...exd5-4.Nc3'},
 'B23': {'name': 'Closed Sicilian Defense Grand Prix Attack 3...e6 4.Nf3',
  'count': 37,
  'link': 'https://www.chess.com/openings/Closed-Sicilian-Defense-Grand-Prix-Attack-3...e6-4.Nf3'},
 'D04': {'name': 'Colle System',
  'count': 37,
  'link': 'https://www.chess.com/openings/Colle-System'},
 'A46': {'name': 'Indian Game Tartakower Defense 3.Nc3 g6',
  'count': 35,
  'link': 'https://www.chess.com/openings/Indian-Game-Tartakower-Defense-3.Nc3-g6'},
 'D10': {'name': 'Slav Defense Exchange Variation 3...cxd5 4.Nf3 Nc6',
  'count': 35,
  'link': 'https://www.chess.com/openings/Slav-Defense-Exchange-Variation-3...cxd5-4.Nf3-Nc6'},
 'E61': {'name': 'Kings Indian Defense Normal Variation 4.Nf3 d6 5.e3',
  'count': 33,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense-Normal-Variation-4.Nf3-d6-5.e3'},
 'B12': {'name': 'Caro Kann Defense Advance Botvinnik Carls Defense 4.c3',
  'count': 31,
  'link': 'https://www.chess.com/openings/Caro-Kann-Defense-Advance-Botvinnik-Carls-Defense-4.c3'},
 'C36': {'name': 'Kings Gambit Accepted Modern Defense 4.exd5',
  'count': 31,
  'link': 'https://www.chess.com/openings/Kings-Gambit-Accepted-Modern-Defense-4.exd5'},
 'A06': {'name': 'Reti Opening 1...d5',
  'count': 31,
  'link': 'https://www.chess.com/openings/Reti-Opening-1...d5'},
 'C24': {'name': 'Bishops Opening Berlin Defense 3.d3 Bc5',
  'count': 29,
  'link': 'https://www.chess.com/openings/Bishops-Opening-Berlin-Defense-3.d3-Bc5'},
 'C10': {'name': 'French Defense Normal Variation 2...d5 3.Nc3 Nc6 4.Nf3',
  'count': 29,
  'link': 'https://www.chess.com/openings/French-Defense-Normal-Variation-2...d5-3.Nc3-Nc6-4.Nf3'},
 'A02': {'name': 'Birds Opening 1...d6 2.Nf3',
  'count': 27,
  'link': 'https://www.chess.com/openings/Birds-Opening-1...d6-2.Nf3'},
 'A07': {'name': 'Kings Indian Attack Yugoslav Variation 3.Bg2 Bf5 4.d3 e6 5.O O',
  'count': 27,
  'link': 'https://www.chess.com/openings/Kings-Indian-Attack-Yugoslav-Variation-3.Bg2-Bf5-4.d3-e6-5.O-O'},
 'C55': {'name': 'Italian Game Two Knights Modern Bishops Opening 4...d5',
  'count': 27,
  'link': 'https://www.chess.com/openings/Italian-Game-Two-Knights-Modern-Bishops-Opening-4...d5'},
 'C37': {'name': 'Kings Gambit Accepted Kings Knight Gambit 3...g5 4.d4',
  'count': 27,
  'link': 'https://www.chess.com/openings/Kings-Gambit-Accepted-Kings-Knight-Gambit-3...g5-4.d4'},
 'B30': {'name': 'Sicilian Defense Old Sicilian Variation 3.Bc4 e6 4.Nc3 a6',
  'count': 25,
  'link': 'https://www.chess.com/openings/Sicilian-Defense-Old-Sicilian-Variation-3.Bc4-e6-4.Nc3-a6'},
 'C21': {'name': 'Center Game',
  'count': 25,
  'link': 'https://www.chess.com/openings/Center-Game'},
 'B21': {'name': 'Sicilian Defense McDonnell Attack 2...Nc6',
  'count': 23,
  'link': 'https://www.chess.com/openings/Sicilian-Defense-McDonnell-Attack-2...Nc6'},
 'C02': {'name': 'French Defense Advance Extended Bishop Swap Variation',
  'count': 21,
  'link': 'https://www.chess.com/openings/French-Defense-Advance-Extended-Bishop-Swap-Variation'},
 'C31': {'name': 'Kings Gambit Declined Falkbeer Countergambit',
  'count': 21,
  'link': 'https://www.chess.com/openings/Kings-Gambit-Declined-Falkbeer-Countergambit'},
 'C40': {'name': 'Kings Pawn Opening Kings Knight Variation',
  'count': 21,
  'link': 'https://www.chess.com/openings/Kings-Pawn-Opening-Kings-Knight-Variation'},
 'C41': {'name': 'Philidor Defense 3.Bc4',
  'count': 21,
  'link': 'https://www.chess.com/openings/Philidor-Defense-3.Bc4'},
 'D06': {'name': 'Queens Gambit',
  'count': 21,
  'link': 'https://www.chess.com/openings/Queens-Gambit'},
 'A05': {'name': 'Reti Opening Kings Indian Attack Symmetrical Defense 3.Bg2 Bg7 4.O O O O',
  'count': 21,
  'link': 'https://www.chess.com/openings/Reti-Opening-Kings-Indian-Attack-Symmetrical-Defense-3.Bg2-Bg7-4.O-O-O-O'},
 'A10': {'name': 'English Opening 1...d6',
  'count': 19,
  'link': 'https://www.chess.com/openings/English-Opening-1...d6'},
 'C46': {'name': 'Three Knights Opening 3...Bc5 4.Nxe5',
  'count': 17,
  'link': 'https://www.chess.com/openings/Three-Knights-Opening-3...Bc5-4.Nxe5'},
 'E90': {'name': 'Kings Indian Defense Normal Variation 4.e4 d6 5.Nf3 O O',
  'count': 15,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense-Normal-Variation-4.e4-d6-5.Nf3-O-O'},
 'B13': {'name': 'Caro Kann Defense Exchange Variation 3...cxd5 4.Nf3 Nc6',
  'count': 15,
  'link': 'https://www.chess.com/openings/Caro-Kann-Defense-Exchange-Variation-3...cxd5-4.Nf3-Nc6'},
 'C33': {'name': 'Kings Gambit Accepted Bishops Gambit Maurian Defense',
  'count': 15,
  'link': 'https://www.chess.com/openings/Kings-Gambit-Accepted-Bishops-Gambit-Maurian-Defense'},
 'D20': {'name': 'Queens Gambit Accepted Central Variation Modern Defense 4.d5 Ne5',
  'count': 13,
  'link': 'https://www.chess.com/openings/Queens-Gambit-Accepted-Central-Variation-Modern-Defense-4.d5-Ne5'},
 'A16': {'name': 'English Opening Anglo Indian Queens Knight Variation 2...g6 3.e4 d6',
  'count': 13,
  'link': 'https://www.chess.com/openings/English-Opening-Anglo-Indian-Queens-Knight-Variation-2...g6-3.e4-d6'},
 'A43': {'name': 'Old Benoni Defense 2.dxc5',
  'count': 13,
  'link': 'https://www.chess.com/openings/Old-Benoni-Defense-2.dxc5'},
 'C45': {'name': 'Scotch Game',
  'count': 11,
  'link': 'https://www.chess.com/openings/Scotch-Game'},
 'A53': {'name': 'Old Indian Defense Janowski Variation',
  'count': 11,
  'link': 'https://www.chess.com/openings/Old-Indian-Defense-Janowski-Variation'},
 'A03': {'name': 'Birds Opening Dutch Variation 2.e3',
  'count': 9,
  'link': 'https://www.chess.com/openings/Birds-Opening-Dutch-Variation-2.e3'},
 'B15': {'name': 'Caro Kann Defense 2.d4 d5 3.Nc3',
  'count': 9,
  'link': 'https://www.chess.com/openings/Caro-Kann-Defense-2.d4-d5-3.Nc3'},
 'E64': {'name': 'Kings Indian Defense...4.g3 d6 5.Bg2 c6 6.O O',
  'count': 7,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense...4.g3-d6-5.Bg2-c6-6.O-O'},
 'C42': {'name': 'Petrovs Defense Three Knights Game',
  'count': 7,
  'link': 'https://www.chess.com/openings/Petrovs-Defense-Three-Knights-Game'},
 'E70': {'name': 'Kings Indian Defense Normal Variation 4.e4 d6',
  'count': 7,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense-Normal-Variation-4.e4-d6'},
 'A42': {'name': 'Modern Defense Averbakh Variation 4...c6 5.Nf3 Nf6',
  'count': 5,
  'link': 'https://www.chess.com/openings/Modern-Defense-Averbakh-Variation-4...c6-5.Nf3-Nf6'},
 'D03': {'name': 'Queens Pawn Opening Torre Attack',
  'count': 5,
  'link': 'https://www.chess.com/openings/Queens-Pawn-Opening-Torre-Attack'},
 'A15': {'name': 'English Opening Anglo Indian Kings Indian Defense...5.O O d6 6.Nc3 Nc6 7.d3',
  'count': 5,
  'link': 'https://www.chess.com/openings/English-Opening-Anglo-Indian-Kings-Indian-Defense...5.O-O-d6-6.Nc3-Nc6-7.d3'},
 'C48': {'name': 'Four Knights Game Spanish Variation Classical Variation',
  'count': 5,
  'link': 'https://www.chess.com/openings/Four-Knights-Game-Spanish-Variation-Classical-Variation'},
 'C15': {'name': 'French Defense Winawer Delayed Exchange Variation 4...Qxd5 5.Nf3 Nf6',
  'count': 5,
  'link': 'https://www.chess.com/openings/French-Defense-Winawer-Delayed-Exchange-Variation-4...Qxd5-5.Nf3-Nf6'},
 'C27': {'name': 'Vienna Game Frankenstein Dracula Variation',
  'count': 5,
  'link': 'https://www.chess.com/openings/Vienna-Game-Frankenstein-Dracula-Variation'},
 'C22': {'name': 'Center Game Accepted Normal Variation',
  'count': 3,
  'link': 'https://www.chess.com/openings/Center-Game-Accepted-Normal-Variation'},
 'A20': {'name': 'English Opening Kings English Variation 2.g3 f5',
  'count': 3,
  'link': 'https://www.chess.com/openings/English-Opening-Kings-English-Variation-2.g3-f5'},
 'C57': {'name': 'Italian Game Knight Attack',
  'count': 3,
  'link': 'https://www.chess.com/openings/Italian-Game-Knight-Attack'},
 'B28': {'name': 'Sicilian Defense OKelly Venice Steiner Line 4.d4',
  'count': 3,
  'link': 'https://www.chess.com/openings/Sicilian-Defense-OKelly-Venice-Steiner-Line-4.d4'},
 'B03': {'name': 'Alekhines Defense Balogh Variation',
  'count': 3,
  'link': 'https://www.chess.com/openings/Alekhines-Defense-Balogh-Variation'},
 'C03': {'name': 'French Defense Tarrasch Variation 3...Ne7 4.Ngf3',
  'count': 3,
  'link': 'https://www.chess.com/openings/French-Defense-Tarrasch-Variation-3...Ne7-4.Ngf3'},
 'C60': {'name': 'Ruy Lopez Opening Cozio Defense 4.Nc3 d6',
  'count': 3,
  'link': 'https://www.chess.com/openings/Ruy-Lopez-Opening-Cozio-Defense-4.Nc3-d6'},
 'C11': {'name': 'French Defense Classical Variation',
  'count': 3,
  'link': 'https://www.chess.com/openings/French-Defense-Classical-Variation'},
 'D31': {'name': 'Queens Gambit Declined Queens Knight Variation',
  'count': 3,
  'link': 'https://www.chess.com/openings/Queens-Gambit-Declined-Queens-Knight-Variation'},
 'B50': {'name': 'Sicilian Defense Delayed Alapin Variation',
  'count': 3,
  'link': 'https://www.chess.com/openings/Sicilian-Defense-Delayed-Alapin-Variation'},
 'D11': {'name': 'Slav Defense Modern Bishops Game',
  'count': 3,
  'link': 'https://www.chess.com/openings/Slav-Defense-Modern-Bishops-Game'},
 'A11': {'name': 'English Opening Caro Kann Defensive System 2.Nc3 d5 3.e3',
  'count': 3,
  'link': 'https://www.chess.com/openings/English-Opening-Caro-Kann-Defensive-System-2.Nc3-d5-3.e3'},
 'A49': {'name': 'Reti Opening Nimzo Larsen Double Fianchetto Attack',
  'count': 3,
  'link': 'https://www.chess.com/openings/Reti-Opening-Nimzo-Larsen-Double-Fianchetto-Attack'},
 'D94': {'name': 'Grunfeld Defense Burille Variation...6.Be2 O O 7.O O Bg4',
  'count': 3,
  'link': 'https://www.chess.com/openings/Grunfeld-Defense-Burille-Variation...6.Be2-O-O-7.O-O-Bg4'},
 'E60': {'name': 'Kings Indian Defense',
  'count': 3,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense'},
 'A54': {'name': 'Old Indian Defense Ukrainian Variation',
  'count': 3,
  'link': 'https://www.chess.com/openings/Old-Indian-Defense-Ukrainian-Variation'},
 'C77': {'name': 'Ruy Lopez Opening Morphy Defense Tarrasch Variation 5...b5 6.Bb3',
  'count': 1,
  'link': 'https://www.chess.com/openings/Ruy-Lopez-Opening-Morphy-Defense-Tarrasch-Variation-5...b5-6.Bb3'},
 'D79': {'name': 'Neo Grunfeld Defense Classical Original Ultra Delayed Exchange Variation 8.Nc3 e6',
  'count': 1,
  'link': 'https://www.chess.com/openings/Neo-Grunfeld-Defense-Classical-Original-Ultra-Delayed-Exchange-Variation-8.Nc3-e6'},
 'A13': {'name': 'English Opening Agincourt Defense 2.b3',
  'count': 1,
  'link': 'https://www.chess.com/openings/English-Opening-Agincourt-Defense-2.b3'},
 'D30': {'name': 'Queens Gambit Declined',
  'count': 1,
  'link': 'https://www.chess.com/openings/Queens-Gambit-Declined'},
 'D21': {'name': 'Queens Gambit Accepted Rosenthal Variation 4.e4',
  'count': 1,
  'link': 'https://www.chess.com/openings/Queens-Gambit-Accepted-Rosenthal-Variation-4.e4'},
 'D38': {'name': 'Queens Gambit Declined Ragozin Defense',
  'count': 1,
  'link': 'https://www.chess.com/openings/Queens-Gambit-Declined-Ragozin-Defense'},
 'E00': {'name': 'Indian Game East Indian Defense',
  'count': 1,
  'link': 'https://www.chess.com/openings/Indian-Game-East-Indian-Defense'},
 'D12': {'name': 'Slav Defense Modern Quiet Schallopp Defense',
  'count': 1,
  'link': 'https://www.chess.com/openings/Slav-Defense-Modern-Quiet-Schallopp-Defense'},
 'D13': {'name': 'Slav Defense Modern Exchange Variation 4...cxd5 5.Nc3',
  'count': 1,
  'link': 'https://www.chess.com/openings/Slav-Defense-Modern-Exchange-Variation-4...cxd5-5.Nc3'},
 'A50': {'name': 'Indian Game Slav Indian Defense',
  'count': 1,
  'link': 'https://www.chess.com/openings/Indian-Game-Slav-Indian-Defense'},
 'A24': {'name': 'English Opening Carls Bremen Fianchetto Line...6.Nge2 O O 7.O O Nc6',
  'count': 1,
  'link': 'https://www.chess.com/openings/English-Opening-Carls-Bremen-Fianchetto-Line...6.Nge2-O-O-7.O-O-Nc6'},
 'D45': {'name': 'Semi Slav Defense Main Line',
  'count': 1,
  'link': 'https://www.chess.com/openings/Semi-Slav-Defense-Main-Line'},
 'C35': {'name': 'Kings Gambit Accepted Cunningham McCormick Defense',
  'count': 1,
  'link': 'https://www.chess.com/openings/Kings-Gambit-Accepted-Cunningham-McCormick-Defense'},
 'B04': {'name': 'Alekhines Defense Modern Larsen Variation 5.Nxe5',
  'count': 1,
  'link': 'https://www.chess.com/openings/Alekhines-Defense-Modern-Larsen-Variation-5.Nxe5'},
 'B51': {'name': 'Sicilian Defense Canal Attack...4.d4 a6 5.Bxd7 Bxd7',
  'count': 1,
  'link': 'https://www.chess.com/openings/Sicilian-Defense-Canal-Attack...4.d4-a6-5.Bxd7-Bxd7'},
 'D46': {'name': 'Semi Slav Defense Main Line Romih Variation 7.O O O O',
  'count': 1,
  'link': 'https://www.chess.com/openings/Semi-Slav-Defense-Main-Line-Romih-Variation-7.O-O-O-O'},
 'C38': {'name': 'Kings Gambit Accepted Traditional Variation 5.d4 d6',
  'count': 1,
  'link': 'https://www.chess.com/openings/Kings-Gambit-Accepted-Traditional-Variation-5.d4-d6'},
 'D07': {'name': 'Queens Gambit Declined Chigorin Defense 3.Nc3 dxc4 4.d5',
  'count': 1,
  'link': 'https://www.chess.com/openings/Queens-Gambit-Declined-Chigorin-Defense-3.Nc3-dxc4-4.d5'},
 'D24': {'name': 'Queens Gambit Accepted Showalter Variation',
  'count': 1,
  'link': 'https://www.chess.com/openings/Queens-Gambit-Accepted-Showalter-Variation'},
 'A57': {'name': 'Benoni Defense Hromadka System',
  'count': 1,
  'link': 'https://www.chess.com/openings/Benoni-Defense-Hromadka-System'},
 'D70': {'name': 'Kings Indian Defense Alekhine Anti Grunfeld Variation 3...Bg7 4.e4 O O',
  'count': 1,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense-Alekhine-Anti-Grunfeld-Variation-3...Bg7-4.e4-O-O'},
 'B11': {'name': 'Caro Kann Defense Two Knights Mindeno Retreat Line 5.exd5 cxd5',
  'count': 1,
  'link': 'https://www.chess.com/openings/Caro-Kann-Defense-Two-Knights-Mindeno-Retreat-Line-5.exd5-cxd5'},
 'D82': {'name': 'Grunfeld Defense Brinckmann Attack 4...Bg7 5.e3 c6',
  'count': 1,
  'link': 'https://www.chess.com/openings/Grunfeld-Defense-Brinckmann-Attack-4...Bg7-5.e3-c6'},
 'B09': {'name': 'Pirc Defense Main Line Austrian Attack 4...Bg7',
  'count': 1,
  'link': 'https://www.chess.com/openings/Pirc-Defense-Main-Line-Austrian-Attack-4...Bg7'},
 'E80': {'name': 'Kings Indian Defense Samisch Variation 5...Nbd7',
  'count': 1,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense-Samisch-Variation-5...Nbd7'},
 'E76': {'name': 'Kings Indian Defense Four Pawns Attack',
  'count': 1,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense-Four-Pawns-Attack'}}

In [4]:
my_games_df = pd.DataFrame(data=my_games)
my_games_df = my_games_df.T
my_games_df = my_games_df[my_games_df["Variant"].isna()]
my_games_df = my_games_df.set_index("EndDate")
my_games_df.index = (pd.to_datetime(my_games_df.index))
my_games_df = my_games_df.loc[my_games_df.index > "2025-02-28", :]
#my_games_df = my_games_df.loc[my_games_df.index < "2026-07-01", :]
my_games_df = my_games_df.drop(my_games_df[my_games_df["TimeControl"].str.startswith("1/")].index)

my_games_df["WhiteElo"] = my_games_df["WhiteElo"].astype(int)
my_games_df["BlackElo"] = my_games_df["BlackElo"].astype(int)


my_games_df["isWhite"] = my_games_df["White"] == username
my_games_df["isBlack"] = my_games_df["Black"] == username
my_games_df["UserColor"] = my_games_df[["isWhite", "isBlack"]].idxmax(axis=1)

my_games_df["Win"] = (
    ((my_games_df["Result"] == "1-0") & my_games_df["isWhite"]) |
    ((my_games_df["Result"] == "0-1") & my_games_df["isBlack"])
)

my_games_df["Loss"] = (
    ((my_games_df["Result"] == "1-0") & my_games_df["isBlack"]) |
    ((my_games_df["Result"] == "0-1") & my_games_df["isWhite"])
)

my_games_df["Tie"] = my_games_df["Result"] == "1/2-1/2"

my_games_df["RelativeResult"] = my_games_df[["Win", "Loss", "Tie"]].idxmax(axis=1)
my_games_df["RelativeEloDiff"] = ((
                                    (my_games_df["WhiteElo"] - my_games_df["BlackElo"]) * (my_games_df["isBlack"].astype(int)) )
                                    +
                                    ( (my_games_df["BlackElo"] - my_games_df["WhiteElo"]) * (my_games_df["isWhite"].astype(int))  ))

my_games_df["Opponent"] = (my_games_df["White"].str.replace(username, "") + my_games_df["Black"].str.replace(username, ""))

my_games_df = add_opening_group(my_games_df)
my_games_df = my_games_df.drop(["Site", "Event", "Round", "Link", "Termination", "ECOUrl", "SetUp", "StartTime", "EndTime", "UTCTime", "UTCDate", "Timezone", "ECO", "FEN", "Variant", "CurrentPosition", "Win", "Loss", "Tie"], axis=1)
my_games_df = my_games_df.drop_duplicates().sort_index()

my_games_df["Opponent"] = my_games_df["Opponent"].str.lower()
my_games_df["White"] = my_games_df["White"].str.lower()
my_games_df["Black"] = my_games_df["Black"].str.lower()

my_games_df.head(2)

,Date,White,Black,Result,WhiteElo,BlackElo,TimeControl,game_pgn,Opening,isWhite,isBlack,UserColor,RelativeResult,RelativeEloDiff,Opponent,Opening_Group
EndDate,,,,,,,,,,,,,,,,
2025-03-13,2025.03.13,xbxaaa,rajakel,1-0,255,115,60,1. e4 {[%clk 0:00:56.1]} 1... e5 {[%clk 0:00:5...,Kings Pawn Opening 1...e5,False,True,isBlack,Loss,140,xbxaaa,King's Pawn Opening
2025-03-13,2025.03.13,benot1615,rajakel,1-0,214,100,60,1. e4 {[%clk 0:00:59.8]} 1... e5 {[%clk 0:00:5...,Vienna Game Falkbeer Variation,False,True,isBlack,Loss,114,benot1615,Vienna Game

In [5]:
opponent_matrix_df = my_games_df.groupby(["Opponent", "RelativeResult"]).agg(count=("Result", "count")).sort_values(["Opponent"], ascending=True)
opponent_matrix_df = opponent_matrix_df.sort_values(["RelativeResult"], ascending=True)
opponent_matrix_df = opponent_matrix_df.pivot_table(
                                                        index="Opponent",
                                                        columns="RelativeResult",
                                                        values="count",
                                                        aggfunc="sum",
                                                        fill_value=0
                                                    )
opponent_matrix_df["TotalGamesPlayed"] = opponent_matrix_df["Loss"] + opponent_matrix_df["Win"] + opponent_matrix_df["Tie"]
opponent_matrix_df = opponent_matrix_df[opponent_matrix_df["TotalGamesPlayed"] >= 10]
opponent_matrix_df

RelativeResult    Loss  Tie  Win  TotalGamesPlayed
Opponent
aaradhyajaggi      113   23  131               267
jaypea1999          17    3    9                29
lracking            13    1    9                23
mohamedelmessidy    25    2   13                40

In [6]:
opponent_matrix_df.to_csv(path_or_buf= "./data/top_opponents.csv", mode= "w")

In [7]:
opponent_profiles_df = pd.read_json("opponent_countries.json")
opponent_profiles_df = opponent_profiles_df.T
opponent_profiles_df = opponent_profiles_df.drop_duplicates()
iso_codes_df = pd.read_csv("data\\ISO_countries.csv")

In [8]:
opponent_profiles_df.head()

              username country_code                           country_url
14144ert      14144ert           PH  https://api.chess.com/pub/country/PH
14ms0rry      14ms0rry           BR  https://api.chess.com/pub/country/BR
30mohit        30mohit           IN  https://api.chess.com/pub/country/IN
aubinios      aubinios           FR  https://api.chess.com/pub/country/FR
abbas_4429  abbas_4429           IR  https://api.chess.com/pub/country/IR

In [9]:
iso_codes_df.head()

,name,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
0,Afghanistan,AF,AFG,4.0,ISO 3166-2:AF,Asia,Southern Asia,NaN,142.0,34.0,NaN
1,Åland Islands,AX,ALA,248.0,ISO 3166-2:AX,Europe,Northern Europe,NaN,150.0,154.0,NaN
2,Albania,AL,ALB,8.0,ISO 3166-2:AL,Europe,Southern Europe,NaN,150.0,39.0,NaN
3,Algeria,DZ,DZA,12.0,ISO 3166-2:DZ,Africa,Northern Africa,NaN,2.0,15.0,NaN
4,American Samoa,AS,ASM,16.0,ISO 3166-2:AS,Oceania,Polynesia,NaN,9.0,61.0,NaN

In [10]:
augmented_opponent_df = pd.merge(
    opponent_profiles_df,
    iso_codes_df,
    how="left",
    left_on="country_code",
    right_on="alpha-2"
)
augmented_opponent_df = augmented_opponent_df.drop(["alpha-2", "alpha-3", "country-code", "country_url", "iso_3166-2", "region-code", "sub-region-code"], axis=1, errors="ignore")
augmented_opponent_df["sub-region"] = np.where(
    augmented_opponent_df["sub-region"] == "Western Asia",
    "Middle East",
    augmented_opponent_df["sub-region"])
augmented_opponent_df.head()

,username,country_code,name,region,sub-region,intermediate-region,intermediate-region-code
0,14144ert,PH,Philippines,Asia,South-eastern Asia,NaN,NaN
1,14ms0rry,BR,Brazil,Americas,Latin America and the Caribbean,South America,5.0
2,30mohit,IN,India,Asia,Southern Asia,NaN,NaN
3,aubinios,FR,France,Europe,Western Europe,NaN,NaN
4,abbas_4429,IR,"Iran, Islamic Republic of",Asia,Southern Asia,NaN,NaN

In [11]:
temp = augmented_opponent_df[["username", "name", "region", "sub-region"]]
temp

,username,name,region,sub-region
0,14144ert,Philippines,Asia,South-eastern Asia
1,14ms0rry,Brazil,Americas,Latin America and the Caribbean
2,30mohit,India,Asia,Southern Asia
3,aubinios,France,Europe,Western Europe
4,abbas_4429,"Iran, Islamic Republic of",Asia,Southern Asia
...,...,...,...,...
4029,zuukishimoto,Philippines,Asia,South-eastern Asia
4030,zxc12348982,"Korea, Republic of",Asia,Eastern Asia
4031,theuaugusto,Brazil,Americas,Latin America and the Caribbean
4032,anaresh45,India,Asia,Southern Asia
4033,gab6405,France,Europe,Western Europe

In [12]:
my_games_df = pd.merge(
    my_games_df.reset_index(),
    temp,
    how="left",
    left_on="Opponent",
    right_on="username"
)
my_games_df = my_games_df.set_index("EndDate")
my_games_df = my_games_df.rename(columns={"name": "Country", "region": "Region", "sub-region": "Subregion"})
my_games_df = my_games_df.drop(columns=["username"], errors="ignore")
my_games_df.head()

,Date,White,Black,Result,WhiteElo,BlackElo,TimeControl,game_pgn,Opening,isWhite,isBlack,UserColor,RelativeResult,RelativeEloDiff,Opponent,Opening_Group,Country,Region,Subregion
EndDate,,,,,,,,,,,,,,,,,,,
2025-03-13,2025.03.13,xbxaaa,rajakel,1-0,255,115,60,1. e4 {[%clk 0:00:56.1]} 1... e5 {[%clk 0:00:5...,Kings Pawn Opening 1...e5,False,True,isBlack,Loss,140,xbxaaa,King's Pawn Opening,United States of America,Americas,Northern America
2025-03-13,2025.03.13,benot1615,rajakel,1-0,214,100,60,1. e4 {[%clk 0:00:59.8]} 1... e5 {[%clk 0:00:5...,Vienna Game Falkbeer Variation,False,True,isBlack,Loss,114,benot1615,Vienna Game,Switzerland,Europe,Western Europe
2025-03-13,2025.03.13,rajakel,kerem7806,1-0,165,100,60,1. d4 {[%clk 0:00:58.2]} 1... e6 {[%clk 0:00:5...,Queens Pawn Opening Zukertort Variation 2...e6...,True,False,isWhite,Win,-65,kerem7806,Queen's Pawn Opening,Türkiye,Asia,Middle East
2025-03-13,2025.03.13,loftzy,rajakel,0-1,100,220,60,1. e4 {[%clk 0:00:58.6]} 1... e5 {[%clk 0:00:5...,Four Knights Game,False,True,isBlack,Win,-120,loftzy,Four Knights Game,Bangladesh,Asia,Southern Asia
2025-03-13,2025.03.13,artemix569,rajakel,0-1,130,270,60,1. e4 {[%clk 0:00:59.1]} 1... e5 {[%clk 0:00:5...,Kings Pawn Opening 1...e5,False,True,isBlack,Win,-140,artemix569,King's Pawn Opening,Ukraine,Europe,Eastern Europe

In [13]:
augmented_opponent_df.to_csv(path_or_buf= "./data/augmented_opponents.csv", mode= "w")
my_games_df.to_csv(path_or_buf= "./data/mygames_dataframe.csv", mode= "w")

## Win rate analysis

In [14]:
winrate_by_opening_df = (my_games_df.to_period("Q").reset_index()
    .groupby(["Opening_Group", "EndDate", "RelativeResult"])
    .agg({"Result":"count"})
 ).reset_index()
winrate_by_opening_df["EndDate"] = winrate_by_opening_df.EndDate.astype(str)


winrate_by_opening_df.sample(10)

            Opening_Group EndDate RelativeResult  Result
364      Sicilian Defense  2026Q2           Loss      14
249      Philidor Defense  2026Q2            Win       1
197        Modern Defense  2026Q2           Loss      10
67           Colle System  2025Q4            Win       7
150         King's Gambit  2026Q4           Loss      24
264          Pirc Defense  2026Q2            Tie       3
273      Ponziani Opening  2025Q2            Tie       1
259          Pirc Defense  2025Q4            Win       7
298  Queen's Pawn Opening  2025Q3            Win      17
129          Italian Game  2025Q1           Loss       1

In [15]:
#openings_df = winrate_by_opening_df.groupby("Opening_Group").sum("Result").nlargest(10, "Result").reset_index()["Opening_Group"]
openings_df = winrate_by_opening_df.groupby("Opening_Group")[["Result"]].sum().nlargest(10, "Result").reset_index()["Opening_Group"]

openings_df

0    Scandinavian Defense
1                   Other
2          French Defense
3            Pirc Defense
4     King's Pawn Opening
5           King's Gambit
6    Queen's Pawn Opening
7          Modern Defense
8             Vienna Game
9        Bishop's Opening
Name: Opening_Group, dtype: str

In [16]:
winrate_by_opening_df = winrate_by_opening_df[winrate_by_opening_df["Opening_Group"].isin(openings_df)]
winrate_by_opening_df = winrate_by_opening_df.pivot_table(
                                                        index=["Opening_Group", "EndDate"],
                                                        columns="RelativeResult",
                                                        values="Result",
                                                        aggfunc="sum",
                                                        fill_value=0
                                                    ).reset_index()
winrate_by_opening_df

RelativeResult     Opening_Group EndDate  Loss  Tie  Win
0               Bishop's Opening  2025Q1     3    0    0
1               Bishop's Opening  2025Q2     5    1    0
2               Bishop's Opening  2025Q3    12    0   10
3               Bishop's Opening  2025Q4    35    3   47
4               Bishop's Opening  2026Q1    17    0   18
..                           ...     ...   ...  ...  ...
71                   Vienna Game  2025Q4    37    5   39
72                   Vienna Game  2026Q1    18    0   19
73                   Vienna Game  2026Q2    17    1   16
74                   Vienna Game  2026Q3     8    2   15
75                   Vienna Game  2026Q4     4    1    7

[76 rows x 5 columns]

In [17]:
winrate_by_opening_df.insert(3, "Winrate", winrate_by_opening_df["Win"] / (winrate_by_opening_df["Win"] + winrate_by_opening_df["Loss"]))
winrate_by_opening_df.insert(4, "Lossrate", winrate_by_opening_df["Loss"] / (winrate_by_opening_df["Win"] + winrate_by_opening_df["Loss"]))

In [18]:
winrate_by_opening_df.head(100)

RelativeResult     Opening_Group EndDate  Loss   Winrate  Lossrate  Tie  Win
0               Bishop's Opening  2025Q1     3  0.000000  1.000000    0    0
1               Bishop's Opening  2025Q2     5  0.000000  1.000000    1    0
2               Bishop's Opening  2025Q3    12  0.454545  0.545455    0   10
3               Bishop's Opening  2025Q4    35  0.573171  0.426829    3   47
4               Bishop's Opening  2026Q1    17  0.514286  0.485714    0   18
..                           ...     ...   ...       ...       ...  ...  ...
71                   Vienna Game  2025Q4    37  0.513158  0.486842    5   39
72                   Vienna Game  2026Q1    18  0.513514  0.486486    0   19
73                   Vienna Game  2026Q2    17  0.484848  0.515152    1   16
74                   Vienna Game  2026Q3     8  0.652174  0.347826    2   15
75                   Vienna Game  2026Q4     4  0.636364  0.363636    1    7

[76 rows x 7 columns]

In [19]:
fig = make_subplots(
    rows=1,
    cols=len(winrate_by_opening_df["Opening_Group"].unique()),
    shared_yaxes=True,
    horizontal_spacing=0.01,
    subplot_titles = winrate_by_opening_df["Opening_Group"].unique(),
    font={"size":10}
)

i=1
for opening in winrate_by_opening_df["Opening_Group"].unique():

    temp_df = winrate_by_opening_df[winrate_by_opening_df["Opening_Group"] == opening]


    px_fig = px.line(data_frame=temp_df, x="EndDate", y="Winrate", labels="Opening")

    fig.add_trace(
        px_fig.data[0],
        row=1,
        col=i
    )
    fig.add_hline(
        y=0.5,
        line_dash="solid",
        line_color="black",
        row=1,
        col=i
    )

    i+=1

fig.update_layout(
    title=dict(text="Opening winrates", automargin=True)
)
fig.show()

In [20]:
winrate_by_opening_df.to_csv(path_or_buf= "./data/winrate_by_opening.csv", mode= "w")

## Cleaning data for openings analysis

In [21]:
historical_openings_df = my_games_df[["Opening", "isWhite", "isBlack", "UserColor", "RelativeResult"]]

In [22]:
historical_openings_df = add_opening_group(historical_openings_df)
historical_openings_df = historical_openings_df.loc[historical_openings_df.index > "2025-02-28", :].drop("Opening", axis=1)
historical_openings_df

            isWhite  isBlack UserColor RelativeResult         Opening_Group
EndDate
2025-03-13    False     True   isBlack           Loss   King's Pawn Opening
2025-03-13    False     True   isBlack           Loss           Vienna Game
2025-03-13     True    False   isWhite            Win  Queen's Pawn Opening
2025-03-13    False     True   isBlack            Win     Four Knights Game
2025-03-13    False     True   isBlack            Win   King's Pawn Opening
...             ...      ...       ...            ...                   ...
2026-10-28    False     True   isBlack           Loss  Scandinavian Defense
2026-10-28    False     True   isBlack           Loss  Scandinavian Defense
2026-10-28     True    False   isWhite            Win      Sicilian Defense
2026-10-28     True    False   isWhite            Win  Scandinavian Defense
2026-10-28    False     True   isBlack           Loss        Modern Defense

[4517 rows x 5 columns]

In [23]:
historical_openings_df.to_csv(path_or_buf= "./data/historical_opening.csv", mode= "w")

In [24]:
monthly = (
    historical_openings_df.groupby(pd.Grouper(freq="ME"))["Opening_Group"]
      .value_counts()
      .unstack(fill_value=0)
)

In [25]:
monthly.to_csv(path_or_buf= "./data/monthly_opening.csv", mode= "w")

In [26]:
monthly = monthly.loc[:, monthly.sum() >= 200]
monthly

Opening_Group,French Defense,King's Gambit,King's Pawn Opening,Modern Defense,Other,Pirc Defense,Queen's Pawn Opening,Scandinavian Defense,Vienna Game
EndDate,,,,,,,,,
2025-03-31,2,0,3,6,8,1,13,1,1
2025-04-30,8,1,8,18,16,30,26,4,1
2025-05-31,66,0,69,31,51,9,8,24,0
2025-06-30,52,0,58,28,36,7,0,23,1
2025-07-31,59,0,64,33,27,7,5,18,0
2025-08-31,65,0,68,24,35,9,7,28,1
2025-09-30,13,0,36,7,29,4,30,81,8
2025-10-31,9,0,6,3,26,7,37,112,28
2025-11-30,6,0,5,1,16,1,22,92,19
2025-12-31,6,0,4,2,31,5,32,99,34
2026-01-31,13,0,17,6,24,4,15,73,17
2026-02-28,6,0,14,1,24,18,8,44,11
2026-03-31,5,0,4,5,17,4,12,25,9
2026-04-30,9,42,7,8,43,33,11,66,12
2026-05-31,6,53,1,10,24,28,19,72,6
2026-06-30,3,44,1,7,23,38,7,41,16
2026-07-31,14,43,0,2,25,33,8,45,14
2026-08-31,11,45,1,3,22,31,2,39,4
2026-09-30,8,44,0,6,17,40,4,38,7
2026-10-31,13,41,1,7,33,59,5,57,12

In [27]:
fig = px.line(monthly, x=monthly.index , y=monthly.columns,
              title='Games by Opening per month',
              labels={"EndDate":"Date", "value":"Number of Games"},
              color_discrete_sequence = px.colors.qualitative.Prism
             )
fig.show()

In [28]:
monthly.to_csv(path_or_buf= "./data/historical_opening.csv", mode= "w")

In [29]:
historical_winrate_df = historical_openings_df.drop(["isWhite", "isBlack"], axis=1).reset_index().set_index("EndDate")
historical_winrate_df = historical_winrate_df.to_period("M").reset_index()

historical_winrate_df = historical_winrate_df.groupby(["UserColor", "EndDate", "RelativeResult"]).agg({"Opening_Group":"count"}).reset_index()

historical_winrate_df =  historical_winrate_df.pivot_table(
                                    index=["UserColor", "EndDate"],
                                    columns="RelativeResult",
                                    values="Opening_Group",
                                    aggfunc="sum",
                                    fill_value=0
                                )
historical_winrate_df = historical_winrate_df.reset_index().sort_values("EndDate", ascending=True)
historical_winrate_df["EndDate"] = historical_winrate_df.EndDate.astype(str)

historical_winrate_both_colors_df = historical_winrate_df[["EndDate", "Loss", "Win"]].groupby("EndDate").sum()
historical_winrate_both_colors_df.insert(2, "Winrate", historical_winrate_both_colors_df["Win"] / (historical_winrate_both_colors_df["Win"] + historical_winrate_both_colors_df["Loss"]))

historical_winrate_white_df = historical_winrate_df[historical_winrate_df["UserColor"] == "isWhite"]
historical_winrate_white_df.insert(3, "Winrate", historical_winrate_df["Win"] / (historical_winrate_df["Win"] + historical_winrate_df["Loss"]))

historical_winrate_black_df = historical_winrate_df[historical_winrate_df["UserColor"] == "isBlack"]
historical_winrate_black_df.insert(3, "Winrate", historical_winrate_df["Win"] / (historical_winrate_df["Win"] + historical_winrate_df["Loss"]))

In [30]:
fig = make_subplots(
    rows=3,
    cols=1,
    shared_xaxes=True,
    vertical_spacing=0.1,
    subplot_titles=["Winrate over time", "White winrate over time", "Black winrate over time"],
    font={"size": 14}
)

############## both colors ##############
px_fig = px.line(data_frame=historical_winrate_both_colors_df.reset_index(), x="EndDate", y="Winrate")
fig.add_trace(
    px_fig.data[0],
    row=1,
    col=1
)
fig.add_hline(
    y=0.5,
    line_dash="solid",
    line_color="black",
    row=1,
    col=1,
    label={
        "text":"50%",
        "textposition":"end",
        "font":{"size":12, "color":"black"},
        "yanchor":"top"
    }
)
fig.add_hline(
    y=historical_winrate_both_colors_df["Winrate"].mean(),
    line_dash="solid",
    line_color="red",
    row=1,
    col=1,
    label={
        "text":"Average winrate",
        "textposition":"end",
        "font":{"size":12, "color":"red"},
        "yanchor":"bottom"
    }
)


############## white ##############
px_fig = px.line(data_frame=historical_winrate_white_df.reset_index(), x="EndDate", y="Winrate")
fig.add_trace(
    px_fig.data[0],
    row=2,
    col=1
)
fig.add_hline(
    y=0.5,
    line_dash="solid",
    line_color="black",
    row=2,
    col=1,
    label={
        "text":"50%",
        "textposition":"end",
        "font":{"size":12, "color":"black"},
        "yanchor":"top"
    }
)
fig.add_hline(
    y=historical_winrate_white_df["Winrate"].mean(),
    line_dash="solid",
    line_color="red",
    row=2,
    col=1,
    label={
        "text":"Average winrate",
        "textposition":"end",
        "font":{"size":12, "color":"red"},
        "yanchor":"bottom"
    }
)


############## black ##############
px_fig = px.line(data_frame=historical_winrate_black_df.reset_index(), x="EndDate", y="Winrate")
fig.add_trace(
    px_fig.data[0],
    row=3,
    col=1
)
fig.add_hline(
    y=0.5,
    line_dash="solid",
    line_color="black",
    row=3,
    col=1,
    label={
        "text":"50%",
        "textposition":"end",
        "font":{"size":12, "color":"black"},
        "yanchor":"top"
    }
)
fig.add_hline(
    y=historical_winrate_black_df["Winrate"].mean(),
    line_dash="solid",
    line_color="red",
    row=3,
    col=1,
    label={
        "text":"Average winrate",
        "textposition":"end",
        "font":{"size":12, "color":"red"},
        "yanchor":"bottom"
    }
)


fig.update_layout(
    title=dict(text="Winrate by color", automargin=False),
    height=800,
)
fig.show()

In [31]:
historical_winrate_both_colors_df.to_csv(path_or_buf= "./data/historical_winrate_both_colors.csv", mode= "w")
historical_winrate_white_df.to_csv(path_or_buf= "./data/historical_winrate_white.csv", mode= "w")
historical_winrate_black_df.to_csv(path_or_buf= "./data/historical_winrate_black.csv", mode= "w")

In [32]:
monthly_white = (
    historical_openings_df.loc[historical_openings_df['isWhite'], :].groupby(pd.Grouper(freq="ME"))["Opening_Group"]
      .value_counts()
      .unstack(fill_value=0)
)
monthly_black = (
    historical_openings_df.loc[historical_openings_df['isBlack'], :].groupby(pd.Grouper(freq="ME"))["Opening_Group"]
      .value_counts()
      .unstack(fill_value=0)
)

monthly_white = monthly_white.loc[:, monthly_white.columns.isin(monthly_white.sum().sort_values(ascending=False).head(5).index)]
monthly_black = monthly_black.loc[:, monthly_black.columns.isin(monthly_black.sum().sort_values(ascending=False).head(5).index)]

monthly_black.head()

Opening_Group,French Defense,Other,Pirc Defense,Queen's Pawn Opening,Scandinavian Defense
EndDate,,,,,
2025-03-31,1,6,1,1,0
2025-04-30,1,12,29,9,0
2025-05-31,58,41,2,5,2
2025-06-30,48,30,0,0,1
2025-07-31,52,15,0,5,1

## Monthly openings used, segmented by color played

In [33]:
fig = go.Figure()

for opening in monthly_white.columns: #white
    fig.add_trace(
        go.Scatter(
                x=monthly_white.index,
                y=monthly_white[opening],
                mode="lines",
                name=opening
            )
    )
fig.update_layout( xaxis_title="Date", yaxis_title="Games Played", title="(White) Openings Played Over Time" )
fig.show()

fig = go.Figure()
for opening in monthly_black.columns: #black
    fig.add_trace(
        go.Scatter(
                x=monthly_black.index,
                y=monthly_black[opening],
                mode="lines",
                name=opening
            )
    )
fig.update_layout( xaxis_title="Date", yaxis_title="Games Played", title="(Black) Openings Played Over Time" )
fig.show()

In [34]:
monthly_white.to_csv(path_or_buf= "./data/historical_opening_white.csv", mode= "w")
monthly_black.to_csv(path_or_buf= "./data/historical_opening_black.csv", mode= "w")

In [35]:
#my_games_df.tail(1)["game_pgn"].values

## Winrate by opponent country

In [87]:
country_winrates_df = (my_games_df
    .groupby(["Country", "RelativeResult"])
    .agg({"Result":"count"})
 ).reset_index()

country_winrates_df = country_winrates_df.pivot_table(
    index=["Country"],
    columns="RelativeResult",
    values="Result",
    aggfunc="sum",
    fill_value=0
).reset_index()

country_winrates_df["Total"] = country_winrates_df["Loss"] + country_winrates_df["Win"] + country_winrates_df["Tie"]
country_winrates_df["Winrate"] = country_winrates_df["Win"] / (country_winrates_df["Loss"] + country_winrates_df["Win"])


country_winrates_df.columns.name = None
country_winrates_df

                   Country  Loss  Tie  Win  Total   Winrate
0              Afghanistan     0    0    4      4  1.000000
1                  Albania     3    1    2      6  0.400000
2                  Algeria     9    0   12     21  0.571429
3           American Samoa     1    0    1      2  0.500000
4                   Angola     1    0    3      4  0.750000
..                     ...   ...  ...  ...    ...       ...
158  Virgin Islands (U.S.)     0    0    1      1  1.000000
159                  Wales     2    0    1      3  0.333333
160                  Yemen     3    0    3      6  0.500000
161                 Zambia     0    1    1      2  1.000000
162               Zimbabwe     3    0    1      4  0.250000

[163 rows x 6 columns]

In [91]:
country_winrates_df[country_winrates_df["Country"] == "Lebanon"]

    Country  Loss  Tie  Win  Total   Winrate
84  Lebanon    32    4   22     58  0.407407

In [110]:
country_winrates_df = country_winrates_df.sort_values(by=["Winrate"])
country_winrates_df.to_csv(path_or_buf= "./data/country_winrates.csv", mode= "w")

In [108]:
country_winrates_df[country_winrates_df["Country"] == "India"]

   Country  Loss  Tie  Win  Total   Winrate
64   India   341   40  411    792  0.546543