In [1]:
import my_functions
from my_functions import *
import pandas as pd
import matplotlib.pyplot as plt

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [2]:
my_games = import_games("rajakel_all_games.pgn")

In [3]:
my_openings = {}

for id, game in my_games.items():
    temp_opening = game["ECO"]
    if temp_opening in my_openings:
        my_openings[temp_opening]["count"] += 1
    else:
        my_openings[temp_opening]  = {"name": game["ECOUrl"].split(r"/")[-1].replace("-", " ") , "count" : 0, "link" : game["ECOUrl"]}
    my_games[id]["Opening"] = my_openings[temp_opening]["name"]
my_openings = dict(sorted(my_openings.items(), key = lambda x : x[1]["count"], reverse = True))
my_openings

{'B01': {'name': 'Scandinavian Defense 2.exd5 e5 3.dxe6',
  'count': 1813,
  'link': 'https://www.chess.com/openings/Scandinavian-Defense-2.exd5-e5-3.dxe6'},
 'C20': {'name': 'Kings Pawn Opening Leonardis Variation',
  'count': 737,
  'link': 'https://www.chess.com/openings/Kings-Pawn-Opening-Leonardis-Variation'},
 'C00': {'name': 'French Defense Knight Variation',
  'count': 641,
  'link': 'https://www.chess.com/openings/French-Defense-Knight-Variation'},
 'B07': {'name': 'Pirc Defense Lions Jaw Variation 3...d5 4.e5 Nfd7 5.f4',
  'count': 515,
  'link': 'https://www.chess.com/openings/Pirc-Defense-Lions-Jaw-Variation-3...d5-4.e5-Nfd7-5.f4'},
 'B00': {'name': 'Kings Pawn Opening',
  'count': 513,
  'link': 'https://www.chess.com/openings/Kings-Pawn-Opening'},
 'A00': {'name': 'Polish Opening 1...e5',
  'count': 407,
  'link': 'https://www.chess.com/openings/Polish-Opening-1...e5'},
 'D00': {'name': 'Queens Pawn Opening 1...d5 2.e3',
  'count': 357,
  'link': 'https://www.chess.com/openings/Queens-Pawn-Opening-1...d5-2.e3'},
 'C25': {'name': 'Vienna Game Max Lange Defense',
  'count': 289,
  'link': 'https://www.chess.com/openings/Vienna-Game-Max-Lange-Defense'},
 'A40': {'name': 'Englund Gambit 2.dxe5',
  'count': 257,
  'link': 'https://www.chess.com/openings/Englund-Gambit-2.dxe5'},
 'C34': {'name': 'Kings Gambit Accepted Fischer Defense 4.Bc4 h6',
  'count': 229,
  'link': 'https://www.chess.com/openings/Kings-Gambit-Accepted-Fischer-Defense-4.Bc4-h6'},
 'C23': {'name': 'Bishops Opening',
  'count': 205,
  'link': 'https://www.chess.com/openings/Bishops-Opening'},
 'B06': {'name': 'Modern Defense with 1 e4 2.d3 Bg7',
  'count': 167,
  'link': 'https://www.chess.com/openings/Modern-Defense-with-1-e4-2.d3-Bg7'},
 'C30': {'name': 'Kings Gambit 2...d6',
  'count': 163,
  'link': 'https://www.chess.com/openings/Kings-Gambit-2...d6'},
 'D02': {'name': 'Queens Pawn Opening Zukertort Variation 2...e6 3.Bf4 c5 4.e3',
  'count': 161,
  'link': 'https://www.chess.com/openings/Queens-Pawn-Opening-Zukertort-Variation-2...e6-3.Bf4-c5-4.e3'},
 'B10': {'name': 'Caro Kann Defense 2.Nf3 d5 3.d3',
  'count': 147,
  'link': 'https://www.chess.com/openings/Caro-Kann-Defense-2.Nf3-d5-3.d3'},
 'C50': {'name': 'Italian Game 3...d6',
  'count': 133,
  'link': 'https://www.chess.com/openings/Italian-Game-3...d6'},
 'C28': {'name': 'Bishops Opening Berlin Vienna Hybrid Variation',
  'count': 105,
  'link': 'https://www.chess.com/openings/Bishops-Opening-Berlin-Vienna-Hybrid-Variation'},
 'B02': {'name': 'Alekhines Defense Maroczy Variation 2...d5',
  'count': 99,
  'link': 'https://www.chess.com/openings/Alekhines-Defense-Maroczy-Variation-2...d5'},
 'A45': {'name': 'Indian Game 2.Nc3',
  'count': 83,
  'link': 'https://www.chess.com/openings/Indian-Game-2.Nc3'},
 'C26': {'name': 'Vienna Game Falkbeer Variation',
  'count': 75,
  'link': 'https://www.chess.com/openings/Vienna-Game-Falkbeer-Variation'},
 'B08': {'name': 'Pirc Defense Classical Variation',
  'count': 73,
  'link': 'https://www.chess.com/openings/Pirc-Defense-Classical-Variation'},
 'C47': {'name': 'Four Knights Game',
  'count': 71,
  'link': 'https://www.chess.com/openings/Four-Knights-Game'},
 'A04': {'name': 'Reti Opening',
  'count': 69,
  'link': 'https://www.chess.com/openings/Reti-Opening'},
 'C44': {'name': 'Ponziani Opening 3...d6 4.d4',
  'count': 69,
  'link': 'https://www.chess.com/openings/Ponziani-Opening-3...d6-4.d4'},
 'B22': {'name': 'Alapin Sicilian Defense 2...e6 3.Nf3 Nf6',
  'count': 65,
  'link': 'https://www.chess.com/openings/Alapin-Sicilian-Defense-2...e6-3.Nf3-Nf6'},
 'B20': {'name': 'Sicilian Defense Bowdler Attack 2...Nc6',
  'count': 57,
  'link': 'https://www.chess.com/openings/Sicilian-Defense-Bowdler-Attack-2...Nc6'},
 'A48': {'name': 'Indian Game East Indian London System 3...Bg7 4.h3 d6',
  'count': 55,
  'link': 'https://www.chess.com/openings/Indian-Game-East-Indian-London-System-3...Bg7-4.h3-d6'},
 'A41': {'name': 'Queens Pawn Opening 1...d6 2.Bf4',
  'count': 53,
  'link': 'https://www.chess.com/openings/Queens-Pawn-Opening-1...d6-2.Bf4'},
 'A01': {'name': 'Nimzowitsch Larsen Attack 1...e6 2.Bb2',
  'count': 45,
  'link': 'https://www.chess.com/openings/Nimzowitsch-Larsen-Attack-1...e6-2.Bb2'},
 'D04': {'name': 'Colle System',
  'count': 37,
  'link': 'https://www.chess.com/openings/Colle-System'},
 'D10': {'name': 'Slav Defense Exchange Variation 3...cxd5 4.Nf3 Nc6',
  'count': 35,
  'link': 'https://www.chess.com/openings/Slav-Defense-Exchange-Variation-3...cxd5-4.Nf3-Nc6'},
 'A06': {'name': 'Reti Opening 1...d5',
  'count': 31,
  'link': 'https://www.chess.com/openings/Reti-Opening-1...d5'},
 'C24': {'name': 'Bishops Opening Berlin Defense 3.d3 Bc5',
  'count': 29,
  'link': 'https://www.chess.com/openings/Bishops-Opening-Berlin-Defense-3.d3-Bc5'},
 'C10': {'name': 'French Defense Normal Variation 2...d5 3.Nc3 Nc6 4.Nf3',
  'count': 29,
  'link': 'https://www.chess.com/openings/French-Defense-Normal-Variation-2...d5-3.Nc3-Nc6-4.Nf3'},
 'A07': {'name': 'Kings Indian Attack Yugoslav Variation 3.Bg2 Bf5 4.d3 e6 5.O O',
  'count': 27,
  'link': 'https://www.chess.com/openings/Kings-Indian-Attack-Yugoslav-Variation-3.Bg2-Bf5-4.d3-e6-5.O-O'},
 'C55': {'name': 'Italian Game Two Knights Modern Bishops Opening 4...d5',
  'count': 27,
  'link': 'https://www.chess.com/openings/Italian-Game-Two-Knights-Modern-Bishops-Opening-4...d5'},
 'C21': {'name': 'Center Game',
  'count': 25,
  'link': 'https://www.chess.com/openings/Center-Game'},
 'B23': {'name': 'Closed Sicilian Defense Traditional Line 3.Bc4',
  'count': 25,
  'link': 'https://www.chess.com/openings/Closed-Sicilian-Defense-Traditional-Line-3.Bc4'},
 'C37': {'name': 'Kings Gambit Accepted Kings Knight Gambit 3...g5 4.d4',
  'count': 25,
  'link': 'https://www.chess.com/openings/Kings-Gambit-Accepted-Kings-Knight-Gambit-3...g5-4.d4'},
 'C40': {'name': 'Kings Pawn Opening Kings Knight Variation',
  'count': 21,
  'link': 'https://www.chess.com/openings/Kings-Pawn-Opening-Kings-Knight-Variation'},
 'C41': {'name': 'Philidor Defense 3.Bc4',
  'count': 21,
  'link': 'https://www.chess.com/openings/Philidor-Defense-3.Bc4'},
 'C01': {'name': 'French Defense Exchange Variation 3...exd5 4.Nc3',
  'count': 21,
  'link': 'https://www.chess.com/openings/French-Defense-Exchange-Variation-3...exd5-4.Nc3'},
 'D06': {'name': 'Queens Gambit',
  'count': 21,
  'link': 'https://www.chess.com/openings/Queens-Gambit'},
 'A02': {'name': 'Birds Opening 1...h6',
  'count': 19,
  'link': 'https://www.chess.com/openings/Birds-Opening-1...h6'},
 'A05': {'name': 'Reti Opening Kings Indian Attack Symmetrical Defense 3.Bg2 Bg7 4.O O O O',
  'count': 19,
  'link': 'https://www.chess.com/openings/Reti-Opening-Kings-Indian-Attack-Symmetrical-Defense-3.Bg2-Bg7-4.O-O-O-O'},
 'C46': {'name': 'Three Knights Opening 3...Bc5 4.Nxe5',
  'count': 17,
  'link': 'https://www.chess.com/openings/Three-Knights-Opening-3...Bc5-4.Nxe5'},
 'B12': {'name': 'Caro Kann Defense Advance Variation 3...Bf5 4.c3 e6',
  'count': 17,
  'link': 'https://www.chess.com/openings/Caro-Kann-Defense-Advance-Variation-3...Bf5-4.c3-e6'},
 'C36': {'name': 'Kings Gambit Accepted Modern Defense',
  'count': 17,
  'link': 'https://www.chess.com/openings/Kings-Gambit-Accepted-Modern-Defense'},
 'A46': {'name': 'Indian Game Knights Variation 2...e6 3.Nc3',
  'count': 15,
  'link': 'https://www.chess.com/openings/Indian-Game-Knights-Variation-2...e6-3.Nc3'},
 'C02': {'name': 'French Defense Advance Paulsen Attack 5...cxd4 6.cxd4',
  'count': 15,
  'link': 'https://www.chess.com/openings/French-Defense-Advance-Paulsen-Attack-5...cxd4-6.cxd4'},
 'B13': {'name': 'Caro Kann Defense Exchange Variation 3...cxd5 4.Nf3 Nc6',
  'count': 15,
  'link': 'https://www.chess.com/openings/Caro-Kann-Defense-Exchange-Variation-3...cxd5-4.Nf3-Nc6'},
 'C33': {'name': 'Kings Gambit Accepted Bishops Gambit Maurian Defense',
  'count': 15,
  'link': 'https://www.chess.com/openings/Kings-Gambit-Accepted-Bishops-Gambit-Maurian-Defense'},
 'A43': {'name': 'Old Benoni Defense 2.dxc5',
  'count': 13,
  'link': 'https://www.chess.com/openings/Old-Benoni-Defense-2.dxc5'},
 'A10': {'name': 'English Opening Great Snake Variation 2.Nc3 Bg7',
  'count': 13,
  'link': 'https://www.chess.com/openings/English-Opening-Great-Snake-Variation-2.Nc3-Bg7'},
 'C31': {'name': 'Kings Gambit Declined Falkbeer Blackburne Attack',
  'count': 13,
  'link': 'https://www.chess.com/openings/Kings-Gambit-Declined-Falkbeer-Blackburne-Attack'},
 'C45': {'name': 'Scotch Game',
  'count': 11,
  'link': 'https://www.chess.com/openings/Scotch-Game'},
 'B21': {'name': 'Sicilian Defense McDonnell Attack 2...Nc6 3.d3 e6',
  'count': 11,
  'link': 'https://www.chess.com/openings/Sicilian-Defense-McDonnell-Attack-2...Nc6-3.d3-e6'},
 'A53': {'name': 'Old Indian Defense Janowski Variation',
  'count': 11,
  'link': 'https://www.chess.com/openings/Old-Indian-Defense-Janowski-Variation'},
 'A03': {'name': 'Birds Opening Dutch Variation 2.e3',
  'count': 9,
  'link': 'https://www.chess.com/openings/Birds-Opening-Dutch-Variation-2.e3'},
 'B15': {'name': 'Caro Kann Defense 2.d4 d5 3.Nc3',
  'count': 9,
  'link': 'https://www.chess.com/openings/Caro-Kann-Defense-2.d4-d5-3.Nc3'},
 'E90': {'name': 'Kings Indian Defense Normal Variation 4.e4 d6 5.Nf3',
  'count': 9,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense-Normal-Variation-4.e4-d6-5.Nf3'},
 'C42': {'name': 'Petrovs Defense Three Knights Game',
  'count': 7,
  'link': 'https://www.chess.com/openings/Petrovs-Defense-Three-Knights-Game'},
 'E70': {'name': 'Kings Indian Defense Normal Variation 4.e4 d6',
  'count': 7,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense-Normal-Variation-4.e4-d6'},
 'D20': {'name': 'Queens Gambit Accepted Central Variation Alekhine System 4.Nc3',
  'count': 7,
  'link': 'https://www.chess.com/openings/Queens-Gambit-Accepted-Central-Variation-Alekhine-System-4.Nc3'},
 'E61': {'name': 'Kings Indian Defense Normal Variation 4.Nf3 d6 5.e3 O O',
  'count': 7,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense-Normal-Variation-4.Nf3-d6-5.e3-O-O'},
 'D03': {'name': 'Queens Pawn Opening Torre Attack',
  'count': 5,
  'link': 'https://www.chess.com/openings/Queens-Pawn-Opening-Torre-Attack'},
 'C48': {'name': 'Four Knights Game Spanish Variation Classical Variation',
  'count': 5,
  'link': 'https://www.chess.com/openings/Four-Knights-Game-Spanish-Variation-Classical-Variation'},
 'A16': {'name': 'English Opening Anglo Indian Queens Knight Variation 2...c6 3.e4 e5 4.Nf3',
  'count': 5,
  'link': 'https://www.chess.com/openings/English-Opening-Anglo-Indian-Queens-Knight-Variation-2...c6-3.e4-e5-4.Nf3'},
 'C27': {'name': 'Vienna Game Frankenstein Dracula Variation',
  'count': 5,
  'link': 'https://www.chess.com/openings/Vienna-Game-Frankenstein-Dracula-Variation'},
 'B30': {'name': 'Sicilian Defense Old Sicilian Variation 3.Bc4 e6 4.Nc3',
  'count': 5,
  'link': 'https://www.chess.com/openings/Sicilian-Defense-Old-Sicilian-Variation-3.Bc4-e6-4.Nc3'},
 'C22': {'name': 'Center Game Accepted Normal Variation',
  'count': 3,
  'link': 'https://www.chess.com/openings/Center-Game-Accepted-Normal-Variation'},
 'A20': {'name': 'English Opening Kings English Variation 2.g3 f5',
  'count': 3,
  'link': 'https://www.chess.com/openings/English-Opening-Kings-English-Variation-2.g3-f5'},
 'C57': {'name': 'Italian Game Knight Attack',
  'count': 3,
  'link': 'https://www.chess.com/openings/Italian-Game-Knight-Attack'},
 'A15': {'name': 'English Opening Anglo Indian Kings Indian Defense...5.O O d6 6.Nc3 Nc6 7.d3',
  'count': 3,
  'link': 'https://www.chess.com/openings/English-Opening-Anglo-Indian-Kings-Indian-Defense...5.O-O-d6-6.Nc3-Nc6-7.d3'},
 'B28': {'name': 'Sicilian Defense OKelly Venice Steiner Line 4.d4',
  'count': 3,
  'link': 'https://www.chess.com/openings/Sicilian-Defense-OKelly-Venice-Steiner-Line-4.d4'},
 'B03': {'name': 'Alekhines Defense Balogh Variation',
  'count': 3,
  'link': 'https://www.chess.com/openings/Alekhines-Defense-Balogh-Variation'},
 'C03': {'name': 'French Defense Tarrasch Variation 3...Ne7 4.Ngf3',
  'count': 3,
  'link': 'https://www.chess.com/openings/French-Defense-Tarrasch-Variation-3...Ne7-4.Ngf3'},
 'C60': {'name': 'Ruy Lopez Opening Cozio Defense 4.Nc3 d6',
  'count': 3,
  'link': 'https://www.chess.com/openings/Ruy-Lopez-Opening-Cozio-Defense-4.Nc3-d6'},
 'C11': {'name': 'French Defense Classical Variation',
  'count': 3,
  'link': 'https://www.chess.com/openings/French-Defense-Classical-Variation'},
 'C15': {'name': 'French Defense Winawer Delayed Exchange Variation 4...Qxd5 5.Nf3 Nf6',
  'count': 3,
  'link': 'https://www.chess.com/openings/French-Defense-Winawer-Delayed-Exchange-Variation-4...Qxd5-5.Nf3-Nf6'},
 'D31': {'name': 'Queens Gambit Declined Queens Knight Variation',
  'count': 3,
  'link': 'https://www.chess.com/openings/Queens-Gambit-Declined-Queens-Knight-Variation'},
 'B50': {'name': 'Sicilian Defense Delayed Alapin Variation',
  'count': 3,
  'link': 'https://www.chess.com/openings/Sicilian-Defense-Delayed-Alapin-Variation'},
 'D11': {'name': 'Slav Defense Modern Bishops Game',
  'count': 3,
  'link': 'https://www.chess.com/openings/Slav-Defense-Modern-Bishops-Game'},
 'A11': {'name': 'English Opening Caro Kann Defensive System 2.Nc3 d5 3.e3',
  'count': 3,
  'link': 'https://www.chess.com/openings/English-Opening-Caro-Kann-Defensive-System-2.Nc3-d5-3.e3'},
 'E60': {'name': 'Kings Indian Defense',
  'count': 3,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense'},
 'C77': {'name': 'Ruy Lopez Opening Morphy Defense Tarrasch Variation 5...b5 6.Bb3',
  'count': 1,
  'link': 'https://www.chess.com/openings/Ruy-Lopez-Opening-Morphy-Defense-Tarrasch-Variation-5...b5-6.Bb3'},
 'D79': {'name': 'Neo Grunfeld Defense Classical Original Ultra Delayed Exchange Variation 8.Nc3 e6',
  'count': 1,
  'link': 'https://www.chess.com/openings/Neo-Grunfeld-Defense-Classical-Original-Ultra-Delayed-Exchange-Variation-8.Nc3-e6'},
 'A13': {'name': 'English Opening Agincourt Defense 2.b3',
  'count': 1,
  'link': 'https://www.chess.com/openings/English-Opening-Agincourt-Defense-2.b3'},
 'D30': {'name': 'Queens Gambit Declined',
  'count': 1,
  'link': 'https://www.chess.com/openings/Queens-Gambit-Declined'},
 'D21': {'name': 'Queens Gambit Accepted Rosenthal Variation 4.e4',
  'count': 1,
  'link': 'https://www.chess.com/openings/Queens-Gambit-Accepted-Rosenthal-Variation-4.e4'},
 'D38': {'name': 'Queens Gambit Declined Ragozin Defense',
  'count': 1,
  'link': 'https://www.chess.com/openings/Queens-Gambit-Declined-Ragozin-Defense'},
 'E00': {'name': 'Indian Game East Indian Defense',
  'count': 1,
  'link': 'https://www.chess.com/openings/Indian-Game-East-Indian-Defense'},
 'D12': {'name': 'Slav Defense Modern Quiet Schallopp Defense',
  'count': 1,
  'link': 'https://www.chess.com/openings/Slav-Defense-Modern-Quiet-Schallopp-Defense'},
 'D13': {'name': 'Slav Defense Modern Exchange Variation 4...cxd5 5.Nc3',
  'count': 1,
  'link': 'https://www.chess.com/openings/Slav-Defense-Modern-Exchange-Variation-4...cxd5-5.Nc3'},
 'A49': {'name': 'Reti Opening Nimzo Larsen Double Fianchetto Attack',
  'count': 1,
  'link': 'https://www.chess.com/openings/Reti-Opening-Nimzo-Larsen-Double-Fianchetto-Attack'},
 'D94': {'name': 'Grunfeld Defense Burille Variation...6.Be2 O O 7.O O Bg4',
  'count': 1,
  'link': 'https://www.chess.com/openings/Grunfeld-Defense-Burille-Variation...6.Be2-O-O-7.O-O-Bg4'},
 'A50': {'name': 'Indian Game Slav Indian Defense',
  'count': 1,
  'link': 'https://www.chess.com/openings/Indian-Game-Slav-Indian-Defense'},
 'A24': {'name': 'English Opening Carls Bremen Fianchetto Line...6.Nge2 O O 7.O O Nc6',
  'count': 1,
  'link': 'https://www.chess.com/openings/English-Opening-Carls-Bremen-Fianchetto-Line...6.Nge2-O-O-7.O-O-Nc6'},
 'D45': {'name': 'Semi Slav Defense Main Line',
  'count': 1,
  'link': 'https://www.chess.com/openings/Semi-Slav-Defense-Main-Line'},
 'C35': {'name': 'Kings Gambit Accepted Cunningham McCormick Defense',
  'count': 1,
  'link': 'https://www.chess.com/openings/Kings-Gambit-Accepted-Cunningham-McCormick-Defense'},
 'E64': {'name': 'Kings Indian Defense...4.g3 d6 5.Bg2 O O',
  'count': 1,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense...4.g3-d6-5.Bg2-O-O'},
 'B04': {'name': 'Alekhines Defense Modern Larsen Variation 5.Nxe5',
  'count': 1,
  'link': 'https://www.chess.com/openings/Alekhines-Defense-Modern-Larsen-Variation-5.Nxe5'},
 'B51': {'name': 'Sicilian Defense Canal Attack...4.d4 a6 5.Bxd7 Bxd7',
  'count': 1,
  'link': 'https://www.chess.com/openings/Sicilian-Defense-Canal-Attack...4.d4-a6-5.Bxd7-Bxd7'},
 'D46': {'name': 'Semi Slav Defense Main Line Romih Variation 7.O O O O',
  'count': 1,
  'link': 'https://www.chess.com/openings/Semi-Slav-Defense-Main-Line-Romih-Variation-7.O-O-O-O'},
 'C38': {'name': 'Kings Gambit Accepted Traditional Variation 5.d4 d6',
  'count': 1,
  'link': 'https://www.chess.com/openings/Kings-Gambit-Accepted-Traditional-Variation-5.d4-d6'},
 'D07': {'name': 'Queens Gambit Declined Chigorin Defense 3.Nc3 dxc4 4.d5',
  'count': 1,
  'link': 'https://www.chess.com/openings/Queens-Gambit-Declined-Chigorin-Defense-3.Nc3-dxc4-4.d5'},
 'D24': {'name': 'Queens Gambit Accepted Showalter Variation',
  'count': 1,
  'link': 'https://www.chess.com/openings/Queens-Gambit-Accepted-Showalter-Variation'},
 'A54': {'name': 'Old Indian Defense Ukrainian Variation',
  'count': 1,
  'link': 'https://www.chess.com/openings/Old-Indian-Defense-Ukrainian-Variation'},
 'A57': {'name': 'Benoni Defense Hromadka System',
  'count': 1,
  'link': 'https://www.chess.com/openings/Benoni-Defense-Hromadka-System'},
 'D70': {'name': 'Kings Indian Defense Alekhine Anti Grunfeld Variation 3...Bg7 4.e4 O O',
  'count': 1,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense-Alekhine-Anti-Grunfeld-Variation-3...Bg7-4.e4-O-O'},
 'B11': {'name': 'Caro Kann Defense Two Knights Mindeno Retreat Line 5.exd5 cxd5',
  'count': 1,
  'link': 'https://www.chess.com/openings/Caro-Kann-Defense-Two-Knights-Mindeno-Retreat-Line-5.exd5-cxd5'},
 'D82': {'name': 'Grunfeld Defense Brinckmann Attack 4...Bg7 5.e3 c6',
  'count': 1,
  'link': 'https://www.chess.com/openings/Grunfeld-Defense-Brinckmann-Attack-4...Bg7-5.e3-c6'},
 'B09': {'name': 'Pirc Defense Main Line Austrian Attack 4...Bg7',
  'count': 1,
  'link': 'https://www.chess.com/openings/Pirc-Defense-Main-Line-Austrian-Attack-4...Bg7'},
 'E80': {'name': 'Kings Indian Defense Samisch Variation 5...Nbd7',
  'count': 1,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense-Samisch-Variation-5...Nbd7'},
 'E76': {'name': 'Kings Indian Defense Four Pawns Attack',
  'count': 1,
  'link': 'https://www.chess.com/openings/Kings-Indian-Defense-Four-Pawns-Attack'}}

In [4]:
my_games_df = pd.DataFrame(data=my_games)
my_games_df = my_games_df.T
my_games_df = my_games_df[my_games_df["Variant"].isna()]
my_games_df = my_games_df.set_index("EndDate")
my_games_df.index = (pd.to_datetime(my_games_df.index))
my_games_df = my_games_df.loc[my_games_df.index > "2024-12-31", :]
#my_games_df = my_games_df.loc[my_games_df.index < "2026-07-01", :]
my_games_df["isWhite"] = my_games_df["White"] == "rajakel"
my_games_df["isBlack"] = my_games_df["Black"] == "rajakel"
my_games_df = add_opening_group(my_games_df)
my_games_df.drop(["SetUp", "FEN", "Variant"], axis=1)
my_games_df.head(2)

,Event,Site,Date,Round,White,Black,Result,CurrentPosition,Timezone,ECO,...,EndTime,Link,game_pgn,Opening,Variant,SetUp,FEN,isWhite,isBlack,Opening_Group
EndDate,,,,,,,,,,,,,,,,,,,,,
2025-01-05,Let's Play!,Chess.com,2024.12.12,-,rajakel,nadiyabdelkarim,0-1,r4rk1/pbp1Qppp/np1pp1q1/8/3P2P1/P1PR2B1/2P1PP2...,UTC,A46,...,12:30:16,https://www.chess.com/game/daily/741260267,1. Nc3 {[%clk 0:00:01.2]} 1... Nf6 {[%clk 0:20...,Indian Game Knights Variation 2...e6 3.Nc3,NaN,NaN,NaN,True,False,Indian Game
2025-01-05,Let's Play!,Chess.com,2024.12.12,-,rajakel,nadiyabdelkarim,0-1,r4rk1/pbp1Qppp/np1pp1q1/8/3P2P1/P1PR2B1/2P1PP2...,UTC,A46,...,12:30:16,https://www.chess.com/game/daily/741260267,1. Nc3 {[%clk 0:00:01.2]} 1... Nf6 {[%clk 0:20...,Indian Game Knights Variation 2...e6 3.Nc3,NaN,NaN,NaN,True,False,Indian Game

In [5]:
my_games_df.columns

Index(['Event', 'Site', 'Date', 'Round', 'White', 'Black', 'Result',
       'CurrentPosition', 'Timezone', 'ECO', 'ECOUrl', 'UTCDate', 'UTCTime',
       'WhiteElo', 'BlackElo', 'TimeControl', 'Termination', 'StartTime',
       'EndTime', 'Link', 'game_pgn', 'Opening', 'Variant', 'SetUp', 'FEN',
       'isWhite', 'isBlack', 'Opening_Group'],
      dtype='object')

In [6]:
my_games_df.to_csv(path_or_buf= "./mygames_dataframe.csv", mode= "w")

## Cleaning data for openings analysis

In [7]:
historical_openings_df = my_games_df[["Opening", "isWhite", "isBlack"]]

In [8]:
historical_openings_df = add_opening_group(historical_openings_df)
historical_openings_df = historical_openings_df.loc[historical_openings_df.index > "2024-12-31", :]
historical_openings_df

,Opening,isWhite,isBlack,Opening_Group
EndDate,,,,
2025-01-05,Indian Game Knights Variation 2...e6 3.Nc3,True,False,Indian Game
2025-01-05,Indian Game Knights Variation 2...e6 3.Nc3,True,False,Indian Game
2025-02-26,Queens Pawn Opening Zukertort Variation 2...e6...,True,False,Queen's Pawn Opening
2025-02-24,Queens Pawn Opening 1...d5 2.e3,True,False,Queen's Pawn Opening
2025-02-21,Kings Pawn Opening,False,True,King's Pawn Opening
...,...,...,...,...
2026-09-01,Pirc Defense Lions Jaw Variation 3...d5 4.e5 N...,False,True,Pirc Defense
2026-09-01,Pirc Defense Lions Jaw Variation 3...d5 4.e5 N...,False,True,Pirc Defense
2026-09-01,Alekhines Defense Maroczy Variation 2...d5,True,False,Alekhine Defense
2026-09-01,Queens Pawn Opening 1...d6 2.Bf4,False,True,Queen's Pawn Opening
2026-09-01,Scandinavian Defense 2.exd5 e5 3.dxe6,False,True,Scandinavian Defense

In [9]:
monthly = (
    historical_openings_df.groupby(pd.Grouper(freq="ME"))["Opening_Group"]
      .value_counts()
      .unstack(fill_value=0)
)
monthly = monthly.loc[:, monthly.sum() >= 200]
monthly

Opening_Group,Bishop's Opening,Englund Gambit,French Defense,King's Gambit,King's Pawn Opening,Pirc Defense,Polish Opening,Queen's Pawn Opening,Scandinavian Defense,Vienna Game
EndDate,,,,,,,,,,
2025-01-31,0,0,0,0,0,0,0,0,0,0
2025-02-28,0,2,0,0,2,2,2,8,0,0
2025-03-31,8,20,4,0,10,2,16,44,2,6
2025-04-30,8,30,18,2,50,76,24,66,16,2
2025-05-31,2,66,140,0,220,22,26,16,48,0
2025-06-30,2,52,104,0,154,14,28,0,46,2
2025-07-31,2,44,118,0,166,14,16,10,36,0
2025-08-31,2,18,132,0,168,20,40,14,60,2
2025-09-30,40,4,26,0,104,8,18,60,162,16
2025-10-31,62,2,18,0,36,14,28,74,224,56
2025-11-30,56,0,12,0,24,2,18,44,184,38
2025-12-31,52,2,12,0,40,10,30,64,198,68
2026-01-31,32,4,26,0,58,8,20,30,146,34
2026-02-28,20,2,12,0,52,36,18,16,88,22
2026-03-31,18,2,10,0,30,8,12,24,50,18
2026-04-30,16,4,18,84,54,66,36,22,132,24
2026-05-31,4,0,12,106,24,56,24,38,144,12
2026-06-30,6,2,6,88,24,76,14,14,82,32
2026-07-31,6,2,28,86,20,66,16,16,90,28
2026-08-31,4,0,22,94,20,62,14,4,82,8
2026-09-30,0,0,4,12,8,26,0,2,16,4

In [10]:
fig = px.line(monthly, x=monthly.index , y=monthly.columns,
              title='Games by Opening per month',
              labels={"EndDate":"Date", "value":"Number of Games"},
              color_discrete_sequence = px.colors.qualitative.Prism
             )
fig.show()

In [11]:
monthly_white = (
    historical_openings_df.loc[historical_openings_df['isWhite'], :].groupby(pd.Grouper(freq="ME"))["Opening_Group"]
      .value_counts()
      .unstack(fill_value=0)
)
monthly_black = (
    historical_openings_df.loc[historical_openings_df['isBlack'], :].groupby(pd.Grouper(freq="ME"))["Opening_Group"]
      .value_counts()
      .unstack(fill_value=0)
)

monthly_white = monthly_white.loc[:, monthly_white.columns.isin(monthly_white.sum().sort_values(ascending=False).head(5).index)]
monthly_black = monthly_black.loc[:, monthly_black.columns.isin(monthly_black.sum().sort_values(ascending=False).head(5).index)]

monthly_black

Opening_Group,French Defense,Pirc Defense,Polish Opening,Queen's Pawn Opening,Scandinavian Defense
EndDate,,,,,
2025-02-28,0,2,2,0,0
2025-03-31,2,2,12,8,0
2025-04-30,2,70,18,22,2
2025-05-31,124,4,26,10,4
2025-06-30,96,0,28,0,2
2025-07-31,104,0,16,10,2
2025-08-31,114,0,38,14,16
2025-09-30,12,2,18,54,136
2025-10-31,4,0,28,74,166
2025-11-30,0,0,18,42,146
2025-12-31,2,0,30,64,152
2026-01-31,0,4,14,30,110
2026-02-28,2,28,8,16,66
2026-03-31,0,6,10,24,38
2026-04-30,2,58,24,20,102
2026-05-31,0,48,18,38,110
2026-06-30,0,74,14,14,56
2026-07-31,0,60,14,16,64
2026-08-31,0,52,12,4,60
2026-09-30,0,24,0,2,8

## Monthly openings used, segmented by color played

In [12]:
fig = go.Figure()

for opening in monthly_white.columns: #white
    fig.add_trace(
        go.Scatter(
                x=monthly_white.index,
                y=monthly_white[opening],
                mode="lines",
                name=opening
            )
    )
fig.update_layout( xaxis_title="Date", yaxis_title="Games Played", title="(White) Openings Played Over Time" )
fig.show()

fig = go.Figure()
for opening in monthly_black.columns: #black
    fig.add_trace(
        go.Scatter(
                x=monthly_black.index,
                y=monthly_black[opening],
                mode="lines",
                name=opening
            )
    )
fig.update_layout( xaxis_title="Date", yaxis_title="Games Played", title="(Black) Openings Played Over Time" )
fig.show()