In [1]:
import pandas as pd

In [4]:
mygames_df = pd.read_csv('data/mygames_dataframe.csv')
mygames_df.head()

,EndDate,Date,White,Black,Result,WhiteElo,BlackElo,TimeControl,game_pgn,Opening,isWhite,isBlack,UserColor,RelativeResult,RelativeEloDiff,Opponent,Opening_Group
0,2025-03-13,2025.03.13,Benot1615,rajakel,1-0,214,100,60,1. e4 {[%clk 0:00:59.8]} 1... e5 {[%clk 0:00:5...,Vienna Game Falkbeer Variation,False,True,isBlack,Loss,114,Benot1615,Vienna Game
1,2025-03-13,2025.03.13,XBXAAA,rajakel,1-0,255,115,60,1. e4 {[%clk 0:00:56.1]} 1... e5 {[%clk 0:00:5...,Kings Pawn Opening Leonardis Variation,False,True,isBlack,Loss,140,XBXAAA,King's Pawn Opening
2,2025-03-13,2025.03.13,artemix569,rajakel,0-1,130,270,60,1. e4 {[%clk 0:00:59.1]} 1... e5 {[%clk 0:00:5...,Kings Pawn Opening Leonardis Variation,False,True,isBlack,Win,-140,artemix569,King's Pawn Opening
3,2025-03-13,2025.03.13,rajakel,kerem7806,1-0,165,100,60,1. d4 {[%clk 0:00:58.2]} 1... e6 {[%clk 0:00:5...,Queens Pawn Opening Zukertort Variation 2...e6...,True,False,isWhite,Win,-65,kerem7806,Queen's Pawn Opening
4,2025-03-13,2025.03.13,Loftzy,rajakel,0-1,100,220,60,1. e4 {[%clk 0:00:58.6]} 1... e5 {[%clk 0:00:5...,Four Knights Game,False,True,isBlack,Win,-120,Loftzy,Four Knights Game

In [22]:
#mygames_df.tail(1)["EndDate"].values[0]
mygames_df.iloc[-1, 0][0:7].replace("-", "/")

'2026/10'

In [30]:
from import_all_chess_dot_com_games import fetch_archives
from import_all_chess_dot_com_games import fetch_opponent_countries

In [ ]:

archive_list = fetch_archives("rajakel")

In [ ]:
archive_list.index("https://api.chess.com/pub/player/rajakel/games/2026/06")

'https://api.chess.com/pub/player/rajakel/games/2026/06'

In [28]:
op = pd.read_json("opponent_countries.json")
op

In [67]:
country_codes = pd.read_csv("data\\ISO_countries.csv")
country_codes.tail()

,name,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
254,Kosovo,XK,NaN,NaN,NaN,NaN,Europe,Eastern Europe,NaN,150.0,151.0
255,Palestine,XP,NaN,NaN,NaN,NaN,Asia,Western Asia,NaN,142.0,145.0
256,Scotland,XS,NaN,NaN,NaN,NaN,Europe,Northern Europe,NaN,150.0,154.0
257,Wales,XW,NaN,NaN,NaN,NaN,Europe,Northern Europe,NaN,150.0,154.0
258,International,XX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
country_codes[country_codes["alpha-2"] == "XP"]

,name,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
255,Palestine,XP,NaN,NaN,NaN,NaN,Asia,Western Asia,NaN,142.0,145.0